language: java

jdk:
- oraclejdk8

# Enable container-based infrastructure + caching
# see http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

cache:
  directories:
  - $HOME/.m2

install:
- mvn -faes .travis.maven.settings.xml clean install
